import jsStringEscape from "js-string-escape";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig, type Plugin } from "vite";

function usableFromWorker(): Plugin {
  return {
    name: "usable-from-worker",
    enforce: "post",
    generateBundle(options, outputBundle) {
      let output = "export const assets = new Map();\n";

      for (const [key, chunk] of Object.entries(outputBundle)) {
        if (chunk.type === "asset") {
          output += `assets.set("${chunk.fileName}", "${jsStringEscape(chunk.source)}");\n`;
        } else if (chunk.type === "chunk") {
          output += `assets.set("${chunk.fileName}", "${jsStringEscape(chunk.code)}");\n`;
        }

        delete outputBundle[key];
      }

      this.emitFile({
        fileName: "index.js",
        type: "asset",
        source: output,
      });

      this.emitFile({
        fileName: "index.d.ts",
        type: "asset",
        source: `/**
 * All of the assets of the observability spa generated by Vite.
 */
export declare const assets: Map<string, string>;`,
      });
    },
  };
}

export default defineConfig({
  plugins: [react(), tailwindcss(), usableFromWorker()],
});
